jobs:
  - job: build
    pool:
      vmImage: ubuntu-20.04
    steps:
      - script: |
          set -e
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --use
          VERSION=`cat VERSION`
          echo "Docker tag is: ${VERSION}"
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --tag adferrand/backuppc --output type=local,dest=test .
        displayName: Build container
      - task: PublishPipelineArtifact@1
        inputs:
          path: $(Build.ArtifactStagingDirectory)
          artifact: docker
        displayName: Store Docker artifact
  - job: unit_tests
    dependsOn: build
    pool:
      vmImage: ubuntu-18.04
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: docker
          path: $(Build.SourcesDirectory)
        displayName: Retrieve Docker artifact
      - script: |
          docker load < docker-backuppc.tar.gz
          mkdir -p ./bin
          curl -fsSL https://goss.rocks/install | GOSS_DST=./bin sh
          GOSS_PATH=./bin/goss GOSS_SLEEP=2 GOSS_FILES_PATH=./tests ./bin/dgoss run adferrand/backuppc
        displayName: Run unit tests
  - job: integration_tests
    dependsOn: build
    pool:
      vmImage: ubuntu-18.04
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: docker
          path: $(Build.SourcesDirectory)
        displayName: Retrieve Docker artifact
      - script: |
          docker load < docker-backuppc.tar.gz
          docker run --name backuppc-integration --detach -p 8080:8080 adferrand/backuppc
          sleep 5
          output=`curl http://backuppc:password@localhost:8080/BackupPC_Admin`
          echo "Expect the backupp configuration page without errors"
          grep "The servers PID is" <(echo $output)
          docker rm -f backuppc-integration
        displayName: Run integration tests
